macos_titlebar_color background
macos_option_as_alt no

tab_bar_edge top

#font
# font_family JetBrains Mono Nerd Font
font_family JetBrains Mono Nerd Font
font_size 22
disable_ligatures always
modify_font cell_height +8px

#window info
background_opacity 1
dynamic_background_opacity yes
background_blur 30 
window_border_width 0  
window_padding_width 10

#misc
copy_on_select yes
shell_integration no-cursor
placement_strategy center

bold_font                   auto
italic_font                 auto
bold_italic_font            auto

scrollback_lines            2000
wheel_scroll_min_lines      1
confirm_os_window_close     0
tab_bar_align left

tab_bar_edge top
tab_bar_align center
tab_bar_style separator
tab_separator "  "
tab_bar_margin_height 0.0 0.0
macos_menubar_title_max_length 20
tab_title_max_length 30
tab_title_template "{index}: {title.split(' ')[0]}"

map command+1 goto_tab 1
map command+2 goto_tab 2
map command+3 goto_tab 3
map command+4 goto_tab 4
map command+5 goto_tab 5 
map command+6 goto_tab 6
map command+7 goto_tab 7
map command+8 goto_tab 8
map command+9 goto_tab 9
map command+0 goto_tab 10

# cursor
# ------------------------------------
cursor_blink_interval       0.5
cursor_stop_blinking_after  0
cursor_trail 0
cursor_shape underline
cursor_shape_unfocused hollow

initial_window_width  1280
initial_window_height 800

fullscreen yes

cmd+shift+t new_tab_with_cwd

map cmd+shift+t new_tab_with_cwd

# ctrl+n nueva ventana, mismo dir
map cmd+n launch --cwd=current --type=os-window
# ctrl+shift+n nueva ventana, home dir
map cmd+shift+n launch --type=os-window
